# Generated by Django 6.0.6 on 2026-07-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
    ]
