# Generated by Django 6.0.6 on 2026-07-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='avatar',
            field=models.ImageField(default='media/avatars/noimages.png', upload_to='group_image/'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='rules',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='topic',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
