# Generated by Django 6.0.6 on 2026-07-09 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0003_alter_studygroup_topic_grouppost_groupresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupresource',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='study_groups.studygroup'),
        ),
    ]
